### ISSUE TITLE
Cannot locate symbol "ethtool_cmd_speed" error, when trying to run application on Android device

### ISSUE THREAD

**Issue by sergkundel** [porthole-ascend-cinnamon/mhddos_proxy_releases#14]
Hello,

I used instruction on IT Army of Ukraine how to use MHDDOS tool on Android device.
I'm using Xiaomi Mi A2 Lite.
All packages were correctly installed, but when I tried to run attack command I got this:
```
~/.../shared/mhddos_proxy $ TERMUX=1 bash runner.sh python --itarmy -t 1500

---------------------Auto-update enabled---------------------
Traceback (most recent call last):
  File "/storage/emulated/0/mhddos_proxy/runner.py", line 25, in <module>
    from src.mhddos import AsyncTcpFlood, AsyncUdpFlood, AttackSettings, main as mhddos_main
  File "/storage/emulated/0/mhddos_proxy/src/mhddos.py", line 23, in <module>
    from . import proxy_proto
  File "/storage/emulated/0/mhddos_proxy/src/proxy_proto.py", line 11, in <module>
    from .proxies import ProxySet
  File "/storage/emulated/0/mhddos_proxy/src/proxies.py", line 10, in <module>
    from .system import fetch, read_or_fetch
  File "/storage/emulated/0/mhddos_proxy/src/system.py", line 27, in <module>
    import psutil
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/init.py", line 102, in <module>
    from . import _pslinux as _psplatform
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_pslinux.py", line 26, in <module>
    from . import _psutil_linux as cext
ImportError: dlopen failed: cannot locate symbol "ethtool_cmd_speed" referenced by "/data/data/com.termux/files/usr/lib/python3.10/site-packages/psutil/_psutil_linux.cpython-310.so"...
```

Attaching versions of installed python libraries:
```
~/.../shared/mhddos_proxy $ pip list
Package            Version
------------------ ---------
aiohttp            3.8.0
aiohttp-socks      0.7.1
aiosignal          1.2.0
async-timeout      4.0.2
asyncstdlib        3.10.0
attrs              22.1.0
certifi            2021.10.8
cffi               1.15.1
charset-normalizer 2.0.12
colorama           0.4.4
cryptography       38.0.0
dnspython          2.2.1
frozenlist         1.3.1
idna               3.3
Jinja2             3.1.2
MarkupSafe         2.1.1
multidict          6.0.2
pip                22.2.2
psutil             5.9.2
pycparser          2.21
pyOpenSSL          22.0.0
python-socks       2.0.3
requests           2.27.1
setuptools         63.2.0
urllib3            1.26.12
yarl               1.7.2
```

I haven't found how to resolve this by myself.
Maybe you have some advice.

Thanks

**Comment by porthole-ascend-cinnamon** [comment]
Hi, you are using the old version that is no longer maintained. Current version does not include Android support either, I'm afraid
